#!/bin/bash

# ==============================================================================
# HotPlex Matrix: Interactive Bot Addition Script
# ==============================================================================
# UX Goal: Premium, Minimalist, Cross-Platform (macOS, Linux, Git Bash)
# Convention over Configuration.
# ==============================================================================

# --- Colors & Styling ---
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
PURPLE='\033[0;35m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# --- Initialization ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

# --- Banner ---
printf "${BLUE}${BOLD}╭──────────────────────────────────────────────────────────────────╮${NC}\n"
printf "${BLUE}${BOLD}│${NC}  ${CYAN}${BOLD}🤖 HotPlex Matrix: Add New Bot Instance${NC}                     ${BLUE}${BOLD}│${NC}\n"
printf "${BLUE}${BOLD}╰──────────────────────────────────────────────────────────────────╯${NC}\n"

# --- 1. Auto-Discovery & Intelligence ---
printf "\n${BOLD}${BLUE}🔍 Step 1: Discovering Environment...${NC}\n"

# naming: hotplex-01, hotplex-02, ...
BOT_INDEX=1
while [ -f ".env-$(printf "%02d" $BOT_INDEX)" ]; do
    ((BOT_INDEX++))
done

BOT_PADDED_INDEX=$(printf "%02d" $BOT_INDEX)
SERVICE_NAME="hotplex-$BOT_PADDED_INDEX"
ENV_FILE=".env-$BOT_PADDED_INDEX"

# Detect next available port (Start at 18081)
BASE_PORT=18081
PORT=$((BASE_PORT + BOT_INDEX - 2))
# Ensure port is not already used in docker-compose.yml
while grep -q ":$PORT:8080" docker-compose.yml; do
    ((PORT++))
done

# Inherit from .env-01
if [ -f ".env-01" ]; then
    DEFAULT_OWNER=$(grep "^HOTPLEX_SLACK_PRIMARY_OWNER=" .env-01 | cut -d= -f2 | tr -d ' ' | tr -d '\r')
    DEFAULT_GITHUB_TOKEN=$(grep "^GITHUB_TOKEN=" .env-01 | cut -d= -f2 | tr -d ' ' | tr -d '\r')
    DEFAULT_IMAGE=$(grep "^HOTPLEX_IMAGE=" .env-01 | cut -d= -f2 | tr -d ' ' | tr -d '\r')
fi

# Generate API Key
NEW_API_KEY=$(LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 64)

printf "  ${GREEN}✓${NC} Bot Index: ${BOLD}${BOT_INDEX}${NC}\n"
printf "  ${GREEN}✓${NC} Target Port: ${BOLD}${PORT}${NC}\n"
printf "  ${GREEN}✓${NC} Generated API Key: ${BOLD}${NEW_API_KEY:0:8}...${NC}\n"

# --- 2. Interactive Prompts ---
printf "\n${BOLD}${BLUE}⌨️  Step 2: Configuration (Mandatory)${NC}\n"

# Mandatory Fields
while [ -z "$HOTPLEX_BOT_ID" ]; do
    printf "  ${YELLOW}Input HOTPLEX_BOT_ID (Slack User ID):${NC} "
    read -r HOTPLEX_BOT_ID
done

while [ -z "$HOTPLEX_SLACK_BOT_TOKEN" ]; do
    printf "  ${YELLOW}Input HOTPLEX_SLACK_BOT_TOKEN (xoxb-...):${NC} "
    read -r HOTPLEX_SLACK_BOT_TOKEN
done

while [ -z "$HOTPLEX_SLACK_APP_TOKEN" ]; do
    printf "  ${YELLOW}Input HOTPLEX_SLACK_APP_TOKEN (xapp-...):${NC} "
    read -r HOTPLEX_SLACK_APP_TOKEN
done

# Optional / Default Fields
printf "\n${BOLD}${BLUE}⚙️  Step 3: Configuration (Defaults)${NC}\n"

printf "  ${CYAN}Primary Owner ID [${DEFAULT_OWNER}]:${NC} "
read -r INPUT_OWNER
HOTPLEX_SLACK_PRIMARY_OWNER=${INPUT_OWNER:-$DEFAULT_OWNER}

printf "  ${CYAN}GitHub Token [${DEFAULT_GITHUB_TOKEN:0:8}...]:${NC} "
read -r INPUT_GH
GITHUB_TOKEN=${INPUT_GH:-$DEFAULT_GITHUB_TOKEN}

printf "  ${CYAN}Docker Image [${DEFAULT_IMAGE:-hotplex:go}]:${NC} "
read -r INPUT_IMG
HOTPLEX_IMAGE=${INPUT_IMG:-${DEFAULT_IMAGE:-hotplex:go}}

# CORS Origins (Optional)
DEFAULT_ORIGINS="http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173"
printf "  ${CYAN}CORS Origins (comma-separated) [${DEFAULT_ORIGINS}]:${NC} "
read -r INPUT_ORIGINS
HOTPLEX_ALLOWED_ORIGINS=${INPUT_ORIGINS:-$DEFAULT_ORIGINS}

BOT_NAME="Bot $BOT_INDEX"
GIT_USER="HotPlex secondary-$BOT_INDEX"
GIT_EMAIL="bot$BOT_INDEX@hotplex.dev"

# Role selection
printf "\n${BOLD}${BLUE}🎭 Step 4: Select Bot Role${NC}\n"
printf "  ${CYAN}Available roles:${NC}\n"
printf "    ${GREEN}1.${NC} go        - Go Backend Engineer\n"
printf "    ${GREEN}2.${NC} frontend  - React/Next.js Frontend Engineer\n"
printf "    ${GREEN}3.${NC} devops    - Docker/K8s DevOps Engineer\n"
printf "    ${GREEN}4.${NC} custom    - User-defined (edit manually)\n"
printf "  ${CYAN}Select role [1-4, default: 1 - go]:${NC} "
read -r INPUT_ROLE
BOT_ROLE_NUM=${INPUT_ROLE:-1}

case "$BOT_ROLE_NUM" in
    1) BOT_ROLE="go" ;;
    2) BOT_ROLE="frontend" ;;
    3) BOT_ROLE="devops" ;;
    4) BOT_ROLE="custom" ;;
    *) BOT_ROLE="go" ;;
esac
printf "  ${GREEN}✓${NC} Selected role: ${BOLD}$BOT_ROLE${NC}\n"

# --- 3. Generate .env File ---
printf "\n${BOLD}${BLUE}📝 Step 4: Writing Configuration Files...${NC}\n"

ENV_FILE="$ENV_FILE"

# Convention: Only bot-specific variables in .env-*
# All other defaults come from common.yml
cat > "$ENV_FILE" <<EOF
# ==============================================================================
# HotPlex Environment Configuration - Bot $BOT_PADDED_INDEX
# Generated by add-bot.sh on $(date)
# ==============================================================================
# Convention over Configuration:
# - Default values are defined in common.yml
# - Only override bot-specific variables here
# ==============================================================================

# --- Identity (Required - Bot-specific) ---
HOTPLEX_BOT_ID=$HOTPLEX_BOT_ID

# --- Core Server ---
HOTPLEX_PORT=8080
HOTPLEX_API_KEY=$NEW_API_KEY

# --- CORS (Optional - for Web UI access) ---
HOTPLEX_ALLOWED_ORIGINS=$HOTPLEX_ALLOWED_ORIGINS

# --- Provider (Optional override) ---
# HOTPLEX_PROVIDER_MODEL=sonnet

# --- Slack Bot (Required - Bot-specific) ---
HOTPLEX_SLACK_BOT_USER_ID=$HOTPLEX_BOT_ID
HOTPLEX_SLACK_BOT_TOKEN=$HOTPLEX_SLACK_BOT_TOKEN
HOTPLEX_SLACK_APP_TOKEN=$HOTPLEX_SLACK_APP_TOKEN
HOTPLEX_SLACK_PRIMARY_OWNER=$HOTPLEX_SLACK_PRIMARY_OWNER

# --- GitHub (Optional - inherit from .env-01 if not provided) ---
# GITHUB_TOKEN=$GITHUB_TOKEN

# --- Git Identity (Optional) ---
GIT_USER_NAME="$GIT_USER"
GIT_USER_EMAIL=$GIT_EMAIL

# --- Orchestration (Auto-detected) ---
COMPOSE_FILE=docker-compose.yml
HOTPLEX_IMAGE=$HOTPLEX_IMAGE
HOST_UID=$(id -u)
EOF

printf "  ${GREEN}✓${NC} Created ${BOLD}$ENV_FILE${NC}\n"

# --- 4. Update docker-compose.yml ---
printf "  ${GREEN}⟳${NC} Updating ${BOLD}docker-compose.yml${NC}...\n"

# Create a block to append
cat >> docker-compose.yml <<EOF

  # ============================================================================
  # Bot $BOT_PADDED_INDEX: Secondary Instance (Auto-added)
  # ============================================================================
  $SERVICE_NAME:
    extends:
      file: common.yml
      service: hotplex-base
    container_name: $SERVICE_NAME
    ports: [ "127.0.0.1:$PORT:8080" ]
    env_file: [ $ENV_FILE ]
    volumes:
      - ~/.hotplex/instances/$HOTPLEX_BOT_ID/storage:/home/hotplex/.hotplex:rw
      - ~/.hotplex/instances/$HOTPLEX_BOT_ID/claude:/home/hotplex/.claude:rw
      - ~/.hotplex/instances/$HOTPLEX_BOT_ID/projects:/home/hotplex/projects:rw
    labels:
      - "hotplex.bot.id=$HOTPLEX_BOT_ID"
      - "hotplex.bot.role=secondary"
EOF

printf "  ${GREEN}✓${NC} Service ${BOLD}$SERVICE_NAME${NC} added to compose file.\n"

# --- 5. Create bot config directory structure ---
printf "  ${GREEN}⟳${NC} Creating ${BOLD}configs/bot-$BOT_PADDED_INDEX/${NC} directory...\n"

BOT_CONFIG_DIR="configs/bot-$BOT_PADDED_INDEX"
mkdir -p "$BOT_CONFIG_DIR/base"

# Copy base templates from ../../configs/base/
if [ -d "../../configs/base" ]; then
    cp -r ../../configs/base/* "$BOT_CONFIG_DIR/base/"
    printf "  ${GREEN}✓${NC} Copied base templates to ${BOLD}$BOT_CONFIG_DIR/base/${NC}\n"
else
    printf "  ${YELLOW}⚠${NC} Base templates not found, skipping...\n"
fi

# Generate slack.yaml with inherits
cat > "$BOT_CONFIG_DIR/slack.yaml" <<EOF
# =============================================================================
# HotPlex Slack Adapter Configuration - Bot $BOT_PADDED_INDEX
# Generated by add-bot.sh on $(date)
# =============================================================================
inherits: ./base/slack.yaml

security:
  permission:
    bot_user_id: \${HOTPLEX_SLACK_BOT_USER_ID}

EOF

# Apply role-based system prompt
if [ "$BOT_ROLE" != "custom" ] && [ -f "../../configs/templates/roles/$BOT_ROLE.yaml" ]; then
    # Extract system_prompt from role template and append to slack.yaml
    SYSTEM_PROMPT=$(sed -n '/^system_prompt:/,/^[a-z]/p' "../../configs/templates/roles/$BOT_ROLE.yaml" | sed '1d;$d')
    printf "%s\n" "" >> "$BOT_CONFIG_DIR/slack.yaml"
    printf "%s\n" "system_prompt: |" >> "$BOT_CONFIG_DIR/slack.yaml"
    printf "%s\n" "$SYSTEM_PROMPT" >> "$BOT_CONFIG_DIR/slack.yaml"
    printf "  ${GREEN}✓${NC} Applied $BOT_ROLE system prompt\n"
else
    printf "  ${YELLOW}⚠${NC} Role template not found, using default\n"
fi

# Generate server.yaml with inherits
cat > "$BOT_CONFIG_DIR/server.yaml" <<EOF
# =============================================================================
# HotPlex Server Configuration - Bot $BOT_PADDED_INDEX
# Generated by add-bot.sh on $(date)
# =============================================================================
inherits: ./base/server.yaml

EOF

printf "  ${GREEN}✓${NC} Created ${BOLD}slack.yaml${NC} and ${BOLD}server.yaml${NC} with inherits\n"

# --- 6. Summary & Next Steps ---
printf "\n${GREEN}${BOLD}✨ Success! Bot $BOT_INDEX is ready to roll.${NC}\n"
printf "──────────────────────────────────────────────────────────────────\n"
printf "  ${BOLD}Bot ID:${NC}   $HOTPLEX_BOT_ID\n"
printf "  ${BOLD}Port:${NC}     $PORT\n"
printf "  ${BOLD}Env File:${NC} $ENV_FILE\n"
printf "──────────────────────────────────────────────────────────────────\n"
printf "\n${YELLOW}Next Step:${NC} Run ${BOLD}make docker-up${NC} from the project root to start all bots.\n\n"
